version: '2'
services:
  xrde2e-ui:
    image: xrde2e-ui:latest
    ports:
      - "80:80"
    depends_on:
      - xrde2e-backend
  xrde2e-client:
    image: xrde2e-client:latest
    depends_on:
      - db
    volumes:
      - /var/xrde2e-client:/my/conf:Z
    environment:
      - JAVA_OPTS=-DpropertiesDirectory=/my/conf/
  xrde2e-backend:
    image: xrde2e-backend:latest
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Dspring.data.mongodb.host=db
  db:
    image: mongo:3.4.0
    command: mongod --dbpath=/data/db --noauth
    ports:
      - "27017:27017"
    volumes:
      - /var/mongodb:/data/db:Z